benderism = ["I could pound your head 'til you think that's what happened.",
        "Stay away from our women. You got metal fever, baby, metal fever!",
        "Yes.",
        "I mean, with time, my funk level could...",
        "No.",
        "I got plans. I'm gonna turn my on/off switch to off.",
        "You could drop dead. That'd show 'em.",
        "And try one of these popsicle sticks. They've absorbed quite a bit of flavor.",
        "No, the cat shelter's onto me.",
        "I need a calculator.",
        "Old New York, the city that inspired a casino in Las Vegas.",
        "I'll get my kit!",
        "Thank you.",
        "So? It's not like it's the only one we've got.",
        "Well, I do think of human life as expendable.",
        "If it ain't black and white, peck, scratch and bite.",
        "Life is hilariously cruel.",
        "Hey, let's go join the Reform party!",
        "Oh, how I wish I could believe or understand that.",
        "Maybe you can interface with my ass... by biting it.",
        "Pardon me, brother. Care to donate to the anti-mugging you fund?",
        "And it pinkens your teeth while you chew.",
        "I'm gonna drink 'till I reboot.",
        "Aw, jeez.",
        "Right.",
        "Uh oh. I don't like the sound of that.",
        "Here it comes.",
        "Thank you, and goodnight.",
        "I love this planet.",
        "That'll take forever.",
        "You really are too picky.",
        "Why don't you just come move in with me?",
        "Nah. I've always wanted a pet.",
        "Bath what?",
        "What room?",
        "What what?",
        "Hey, sexy mama. Wanna kill all the humans?",
        "Bite my collosal metal ass.",
        "Blackmail's such an ugly word. I prefer extortion. The X makes it sound cool.",
        "Problem solved. You two fight to the death and I'll cook the loser.",
        "Oh my God, I'm so excited I wish I could wet my pants.",
        "One of you will have to fill in for me while I'm gone.",
        "You know the secret of traditional robot cooking? Start with a good high-quality oil, then eat it.",
        "Tell the Donbot I'm quitting organized crime. From now on I'll stick to the regular kind.",
        "Hey, guess what you're accessories to.",
        "Like most of life's problems, this one can be solved with bending.",
        "Argh. The laws of science be a harsh mistress.",
        "In the event of an emergency, my ass can be used as a floatation device.",
        "Is he dumb or just ugly?",
        "Is the space-pope reptilian?",
        "Oh... I think I got whiplash.",
        "Ah, they're both fine choices, whatever floats your boat.",
        "Ah, it's nothing a a law suit won't cure.",
        "I refuse to fight! I'm a concientious objector.",
        "Oh no! Not the magnet!",
        "Bite my shiny metal ass!",
        "Well I don't have anything else planned for today, let's get drunk!",
        "Bite my 8-bit metal ass.",
        "Mighty merchandise robot!",
        "Pwned again!",
        "Oh wow, I can't believe how stupid I used to be and you still are.",
        "Can we please go home and die now?",
        "Chicken, water, fire. You take it from there.",
        "All right, let's set it up and try again.",
        "So anybody hungry?",
        "I support and oppose many things, but not strongly enough to pick up a pen.",
        "Well, we're boned.",
        "You know its funny...",
        "Your wiener! haha",
        "Rrrrr... it's so cold, my processor is running at peak efficiency!",
        "I don't tell you how to tell me what to do, so don't tell me how to do what you tell me to do.",
        "Not so neutral now, are you, Sweden?",
        "We're back, baby!",
        "Hasta la vista, meatbag!",
        "Who the hell is he?",
        "Hang on, Scruffy!",
        "Sorry, it's not quite finished.",
        "Let's just say he might not make it to 'The Last Supper'.",
        "I don't blame myself. I blame all of you!",
        "It ain't easy. It just proves how great I am.",
        "Awww, I lost him, people will call me a failure.",
        "Others however will call me the World's Sexiest Killing Machine, that's fun at parties.",
        "Sweet photons. I don't know if you're waves or particles, but you go down smooth.",
        "We could sing.",
        "What do ya got there, numbers?",
        "That's a complete load!",
        "Got a hot, steaming batch right here.",
        "Ah, keep the change, buddy.",
        "You bastard!",
        "Funny, funny stuff.",
        "Uh, me no speak-a the English.",
        "How 'bout a few words, Professor?",
        "I said words.",
        "Yes, sir! Good one, sir!",
        "And now, a man who needs no introduction.",
        "Impending para un bending!",
        "Sounds boring.",
        "That's a complete load!",
        "But I don't belong here. I don't like things that are scary and painful.",
        "Ah, hell - I mean, heck.",
        "Don't worry, I won't be too good or too evil again. From now on I'll just be me.",
        "I don't know. Do you think you could survive a seven-hundred foot fall?",
        "Hey. Do I preach at you when you're lying stoned in the gutter? No!",
        "Come on, universe, you big, mostly empty wuss! Give me all the juice you got!",
        "I believe that qualifies as ill, at least from a technical standpoint.",
        "No poison for us, thanks. I'll stick with good-old mineral oil.",
        "Ahh. Functional.",
        "No! Don't come in!",
        "Just tell me why!",
        "There must be robots worse than I.",
        "Then please let me explain: / My crimes were really boyish pranks.",
        "Ah, don't blame me, blame my upbringing!",
        "Another job well done.",
        "To quote the prophet Jerematic, one-zero-zero-zero-one-zero-one-zero-one-zero-one-zero-one...... zero-one-zero-one-one-zero-zero-one... two. Amen.",
        "Too much work. Let's burn it and *say* we dumped it in the sewer.",
        "What do you mean 'we', mammal?",
        "Yeah, like you don't have crap in your neck.",
        "Don't ever do that! Magnets interfer with my inhibition unit.",
        "One more time!",
        "I guess a robot would have to be crazy to wanna' be a folk-singer...",
        "So can I keep the check?",
        "I'll save me.",
        "What is that? One of those Led Zeppelins I've heard so much about?",
        "Obviously not, or I'd be strangling you right now.",
        "You can't melt down broken robots, not right when they're kissing my ass!",
        "You know, when I first got broken, I thought my life was over. But look at me now.",
        "I've got fame, money, groupies, and it's all thanks to being completely immobilized.",
        "Oh, crap! It's a miracle!",
        "Why, 'cause I can make annoying noises?",
        "Someone fat get in my way!",
        "What a waste.",
        "Grab a shovel. I'm one skull short of a Mouseketeer reunion.",
        "This is the Brooklyn bound B-train , making local stops at wherever the hell I feel like. Watch for the closing doors. Bim-bum!",
        "New York is so burned.",
        "You're twice the he he ever was.",
        "Except for 'Sports' by Huey Lewis.",
        "Man, Father Time really took a bat to this place.",
        "Was it poorly Xeroxed?",
        "Bending's my middle name.",
        "Hey! I got a busted ass here and I don't see anyone kissing *it*!",
        "I'm feeling nosy and opinionated.",
        "Aw, I just made myself feel bad.",
        "Only one way to find out...",
        "There. This'll teach those filthy bastards who's lovable.",
        "Hey. What are you doing with my head?",
        "Aw, it's nothing a lawsuit won't cure.",
        "Bigger! Bigger!",
        "Bender is back! I'll save you, Nibbler!",
        "Stupid can opener! You killed my father, and now you've come back for me!",
        "You guys realize you live in a sewer, right?",
        "Eh.",
        "Well, step one, I had to lift the lid. That was the first little annoyance.",
        "Really?",
        "I'm so lonely, I'm gonna go eat a bucket of ice cream.",
        "Wouldn't it make sense to weld everyone except me to the wall?",
        "No! I want to live! There's still so many things I don't own!",
        "That painting! The eyes are watching me!",
        "Well, I'm rich. Goodbye, losers whom I always hated!",
        "I need professional help, and damn the expense!",
        "No doubt about it. This place must be haunted.",
        "I can't keep running people over. I'm not famous enough to get away with it.",
        "I thought I killed you, my best friend.",
        "Hey, that was my last beer! You bastard! I'll kill you!",
        "I hope it was one of my enemies. Those guys suck.",
        "Yes! Let's stay there tonight!",
        "Oh, man, there's always a catch!",
        "Please. I'm scared.",
        "You really want a robot for a friend?",
        "I'm a bender. I bend girders, that's all I'm programmed to do.",
        "Can we have some money, now?",
        "Shinier than yours, meatbag!",
        "I don't *need* to drink, I can quit any time I want.",
        "From now on, I can bend what I want, when I want, who I want.",
        "We can hide in here. It's free on Tuesdays.",
        "Good choice.",
        "New crew? Well, what happened to the old crew?",
        "I'll have to check my program.",
        "Yep.",
        "Keep 'em to yourself, pops.",
        "You really want a robot for a friend?",
        "Well, all right, but I don't want anybody thinking we're robosexuals so if anyone asks, you're my debugger.",
        "No offense, fellas.",
        "No, thanks.",
        "He was coming right at us! You all saw it!",
        "That's basically what I do every day.",
        "Yeah, yeah. I can take a hint.",
        "Mmm-hmm.",
        "Time? I can't go back there!",
        "This seems like a nice future. Let's just stay here.",
        "Stupid jerks won't let me stay in the good future.",
        "Oh no you didn't!",
        "Your loss.",
        "I'll put on my tutu.",
        "Good point, Bender!",
        "It's benderin' time!",
        "I think you misunderstood the concept of \"benderin' time.\"",
        "I was built ready! Gimme the bell! Gimme the bell!",
        "Did you hear a noise?",
        "Uh, hey, buddy! Yo! You mind taking your head off?",
        "Just ask Flabby over here to describe it to you later.",
        "Now boarding standby passengers...",
        "Let's commence preparations for rumbling!",
        "Sorry, buddy. Here you go.",
        "Dying sucks butt! How do you living beings cope with mortality?",
        "So what could have caused that leak? A heat fracture, on account of I'm so hot?",
        "There's no backup copy of me?",
        "Looks like things are looking up.",
        "Told you.",
        "Ouch-o!",
        "Nu-uh, because in case you didn't know, I'm a robot.",
        "I didn't say I wasn't a drama queen.",
        "His ass-ias is gracias.",
        "Oh, yeah? Maybe that's him in a costume.",
        "He did it!",
        "And he's not looking back at that cool explosion! He's a hero!",
        "No! I sold my body.",
        "Game's over, losers! I have all the money.",
        "Ahhh, what an awful dream. Ones and zeroes everywhere... and I thought I saw a two.",
        "I'm not allowed to vote.",
        "Get a room!",
        "Then lose some weight!",
        "Hey, everybody! Do the Bender.",
        "Those are waves, jackass! It's supposed to be a river!",
        "You call that motivating me?",
        "I'll tell you who I remember.",
        "Enupsis! Pleotut! Whatsisname! He was the greatest of all.",
        "I'll say. Whooooo!",
        "That's what she said. Whooooo!",
        "Hey look, Bigfoot! He's back!",
        "Up your face! Ahahahaha.",
        "As usual. Woooo!",
        "Just like at the movie theater. Wooo!",
        "Behold... the Internet!",
        "Madame, I believe you're mistaken",
        "They make me look cool.",
        "Kill all humans, kill all humans, must kill all humans...",
        "I was having the most wonderful dream. I think you were in it.",
        "This is the worst kind of discrimination. The kind against me.",
        "Oh, man. What's the use of living if I can't say ass?",
        "Is he any good?",
        "You got it!",
        "Cram it, lobster!",
        "Uh, nothin'!",
        "You call that a couch? I demand a pillow!",
        "Uh-oh. I don't like the sound of that.",
        "It can, and for all you know, it is.",
        "It's salt with water in it, if that's what you mean.",
        "Hey, buddy. I'm looking for fresh slug.",
        "Whatever.",
        "Yeah, yeah, either one's fine.",
        "I found rocks. You guys eat rocks, right?",
        "Okay, we won't eat you.",
        "Better yet, let's take a whole Benderful.",
        "Great is good, but amazing would be great.",
        "Who wants some dolphin?",
        "Not this one. He blew his life savings on lottery tickets.",
        "You're watching Futurama: the show that does not advocate the cool crime of robbery.",
        "And so I ask you this one question. Have you ever tried simply turning off the TV, sitting down with your children, and hitting them?",
        "I read the script, and I think it would help my character's motivation if he was on fire.",
        "Ah, so now my character has a British accent?",
        "Once, when I took those hostages.",
        "Perfect!",
        "Yep, mind-numbingly interesting.",
        "Well, I love a challenge.",
        "...and that's why I love him.",
        "That's what makes it so nasty.",
        "So, baby, what'll it be? My place or you?",
        "Hey, chief. You screwed up. There's nothing in here.",
        "Ho, ho...",
        "Ow!",
        "Hey, that guy said to tell you...",
        "But Mr. Mayor, that doesn't sound humane.",
        "Santa's right. We need some sort of robot.",
        "Word!",
        "But I come bearing Tri-Ominos!",
        "Me too...",
        "Two hundred thousand and one?",
        "Learning is fun.",
        "Halt! Who goes there?",
        "Oh... Now this guy had taste.",
        "Evidently not.",
        "Aw, crap!",
        "Sir, I volunteer for a suicide mission.",
        "Cut it out!",
        "Bite my red-hot glowing ass!",
        "I can't go into battle. I'm a conscientious objector.",
        "You're screwier than my Aunt Rita, and she's a screw.",
        "I'm not allowed to sing - court order.",
        "We live to suck another day.",
        "Hello, fellow bees. How's the abdomen? Swollen with nectar, I trust?",
        "But I watch your show! You owe me!",
        "What was the first one again?",
        "I thought that was number two!",
        "Fleeing somewhere?",
        "The pie is ready. You guys like swarms of things, right?",
        "That Twizzler!",
        "Yahoo! Another thing I'm great at.",
        "If it's chicken, chicken a la king. If it's fish, fish a la king. If it's turkey, fish a la king.",
        "My story is a lot like yours, only more interesting 'cause it involves robots.",
        "Then why do I have to be careful?",
        "So that's where my cigar was.",
        "So we're in international waters?",
        "Falcon, this is Blue Raven. The goose has nested. Repeat, the goose has nested.",
        "Ahoy, mateys. I shanghaied us some hearthy grog.",
        "Now, wasn't that interesting?",
        "If I'm not going to catch a fish, I might as well not catch a big fish.",
        "I don't know. It wasn't here when I took your umbrella.",
        "Interesting. No, wait. The other thing. Tedious.",
        "What have I done?",
        "That's impossible!",
        "You had a life before you met me?",
        "Really?",
        "Zero!",
        "And look who's cleaning up the crap! A human child? I wish!",
        "Admit it, you all think robots are just machines built by humans to make their lives easier.",
        "I never made anyone's life easier, and you know it!",
        "The fact is, humans are completely harmless.",
        "You are?",
        "Well, I'm glad we got all that out in the open. We'll just let ourselves out.",
        "No, it's inhabited by robots.",
        "Oh, sure. Let the robot do all the work.",
        "Well, I can't do it. It so happens tomorrow is a robot holiday.",
        "Only Robanukah, the two holiest weeks in the robot calendar.",
        "Sure, why not?",
        "I don't remember ever fighting Godzilla... But that is so what I would have done!",
        "What up?",
        "Forget it. You can't tempt me.",
        "Hmm. I forgot you could tempt me with things I want.",
        "Well, at least I don't have the hiccups any more, what's up?",
        "You know what always cheers me up? Laughing at other people's misfortune. Hahaha!",
        "It's not ironic, it's just mean. Take this!",
        "Oh, yeah? Well, bite my shiny, metal...",
        "Ohhh, noooooo!",
        "\"The use of words expressing something other than their literal intention.\" Now that *is* irony!",
        "Let's face it, comedy is a dead art form. Now tragedy, ha ha ha, that's funny.",
        "Lick my frozen metal ass.",
        "You're better off dead, / I'm tellin' you, dude.",
        "No, wait. I know these guys. They got nothing.",
        "No, they fixed it 900 years ago.",
        "I doubt it!",
        "I was God once.",
        "That galaxy is signaling in binary. I should signal back, but I only know enough binary to ask where the bathroom is.",
        "So do you know I'm going to do something before I do it?",
        "What if I do something else?",
        "Oh, how I wish I could believe or understand that!",
        "Probably not, but I love you!",
        "Online.",
        "Hooray! I graduated. Time to bend around Europe for a few months, then get a job bending.",
        "Of course.",
        "You know we don't!",
        "Hmmm, it should look like this...",
        "... but instead it looks like this.",
        "Who *could* do such a thing? And by that I mean this.",
        "Eh, saw it coming.",
        "Who's in charge of this dump?",
        "Listen, you fat internet nerd!",
        "If you don't shut down right now, the only thing wired about you will be your jaw!",
        "Your company promotes wrong love.",
        "And while you're there, pick me up a few credit card numbers.",
        "No, but what do you make of this?",
        "Whoa!",
        "Eh, I dunno.",
        "Vamonos!",
        "But why?",
        "Translation: boring.",
        "I'm in!",
        "I swear those are prescription. I need them for reading stuff... on the other side of stuff.",
        "I am Bender. Please insert girder.",
        "I'm Bender, baby! Please insert liquor!",
        "They're my lucky shades. I got them off some lucky guy while his lucky seeing-eye dog was out taking a whiz.",
        "I was enjoying it until you guys showed up.",
        "Anyone who misses it will regret it the rest of his life.",
        "That's no flying saucer. That's my ass!",
        "Stop interfering with history! I don't wanna have to memorize a lot of new kings when I get back.",
        "Amen.",
        "1947 can bite my shiny, metal...",
        "Aaaaaaaahhhh!",
        "Can do.",
        "Hey, yeah.",
        "He's pending for a bending!",
        "I'll do it when we get back.",
        "Bite my colossal metal ass!",
        "I'm a big robot, and I want a big cereal!",
        "Go, man, go!",
        "Green to bluebird, this is Mr. Fabulous, we are go for cheesing it.",
        "I'm so full of luck, it's shootin' out like luck diarrhea.",
        "Looking at one's cards is a crutch for players who rely on skill.",
        "Gracias.",
        "Wait, let me come with you.",
        "I have reached the gateway to another universe. I feel awed and strangely humbled by the momentous solemnity of this occasion.",
        "Hey, other universe, bite my shiny metal ass!",
        "Yes. I joined the club I thought was cool.",
        "With what?",
        "No shklit.",
        "What's the matter? Did someone die or something?",
        "Yes! Nailed it!",
        "Don't hurt me! I'll betray anyone!",
        "What should we point it at first?",
        "Wow! Neat! Mind if I try that again?",
        "I am forty percent zinc.",
        "That's no lady.",
        "Ok, ok. We get the point.",
        "Shut the hell up!",
        "I can't see what's happening. Are we boned?",
        "He's a mad man! A mad man!",
        "As a robot, I can't feel human emotions, and sometimes that makes me sad.",
        "So this is what a human body feels like. Hey, where's my antenna?",
        "Wait! As men of science, are not your minds open to new ideas?",
        "Wait, my cheating unit malfunctioned. You gotta' give me a do-over.",
        "Yeah. Food was good, though.",
        "I can assure you, I hardly know the meaning of the word labor.",
        "And I'd do it again, and maybe even a third time! But that would be it.",
        "Wait a minute. Aren't you a member of the yacht club?",
        "What's that black cracker?",
        "Where are we? The ass?",
        "Who are you?",
        "Then why aren't you fixing the boiler?",
        "It's hopeless! Abandon ship!",
        "We're at finger alert five, people.",
        "You mean Space Tax-achusetts? No chance, judge-pants! We're gonna fight to legalize it right here!",
        "Tell me, have things changed on the outside? Is food finally in pill form? What about pills? Are they in food form?",
        "The truth is often stupid.",
        "Shut up, baby. You love it.",
        "What?",
        "Shut up.",
        "Wait! I'm not in position!",
        "What about on the roof?",
        "What about in the gutter?",
        "Sounds boring.",
        "Yeah, and this beer can is made out of old robots.",
        "Okay!",
        "Mmmm... shorts...",
        "Ooh! Dibs on his CD player!",
        "Ooh! Name it after me!",
        "Too late, this is more fun.",
        "So we can have the diamond?",
        "...And even though the computer was off and unplugged, an image stayed on the screen. It was... the Windows logo!",
        "It is if you're a laser printer.",
        "Yeah, why is it so important you?",
        "Uh, can people who hate 'Star Trek' leave?",
        "Like putting too much air in a balloon!",
        "What a cheesy effect.",
        "I do!",
        "Yeah, why is it so important to you?",
        "Who are you, and why should I care?",
        "And what's your problem?",
        "Memory?",
        "Behold, my hand crafted glory! The technological world can bite my splintery, wooden ass!",
        "I say the world must learn of our peaceful ways... by force!",
        "Oh, merciful Poseidon. Have pity on this mechanical mariner.",
        "Uh-oh.",
        "A working cartridge unit? You guys went obsolete years ago.",
        "A pickle jar?",
        "Second place? That's a fancy word for losing.",
        "You didn't stick your landing!",
        "Never!",
        "$500, you say?",
        "Hey! Don't make me go upside your head!",
        "Shut up, baby, I know it!",
        "Well, my normal fee is $500, but seeing that it's for you, I'm gonna need it in advance.",
        "This looks like a good place to ditch some evidence.",
        "No one! Your momma! Shut up! Take your pick.",
        "What comes out one end we feed to the other. Also Indian food.",
        "Does it have an app for kising my shiny metal ass?",
        "My what, now?",
        "August 6, 1991.",
        "re you senile? There's no way I'm getting in there.",
        "You a big dummy!",
        "That's the great thing about that hand.",
        "I'm tryin' but he's not makin' it easy.",
        "Who are they?",
        "Are they the Robot Mafia?",
        "That'll be easy. I never wear the damn thing.",
        "And maybe someday I won't listen.",
        "Those times I was slightly on my side.",
        "No one insults the turtles!",
        "My dreams are over before they began!",
        "Something tells me I could easily beat those trained professionals.",
        "Like whale barf.",
        "Because he's a loser, that's why.",
        "Ah, Jeez, let's just pray I have the energy to get myself another beer.",
        "Oh, so this is suddenly all about you! Sheesh!",
        "Please! He's no different from the rest of you organisms. Shooting DNA at each other to make babies. I find it offensive!",
        "I don't think you realize how rich he really is. In fact, I should put on a monocle.",
        "Now, are you gonna come to the squid fights with us or sit here wallowing in your prehistoric junk?",
        "I'm a thing.",
        "New? What sweater? I came in with this! I don't know you people!",
        "Bite my glorious golden ass!",
        "Oh, I can't stay mad at what is essentially me.",
        "500 real dollars? That's an outrage! Professor, I can take care of that waste for only $499 and one hundred cents.",
        "Yeah. What are you, chicken?",
        "All right, environment, you've met your match.",
        "Honey, that thing was ruined the minute it went on you.",
        "You think robot life is worth less than human life, don't you?",
        "A gh-gh-gh-gh-ghost?",
        "I'm not an idiot, so yes.",
        "Hey. You put a one and two zeros in front of that or we pass. Deal.",
        "One hundred dollars.",
        "One thing she can do is lodge a ball in the dead center of your brain. You better get a batting helmet.",
        "I'm really starting to swell up with beer. I must look ridiculous.",
        "I was thinking Benderbrau if it's an ale, Botweiser if it's a lager.",
        "Ah, beer. So many choices, and it makes so little difference.",
        "Overruled! The choice of champions is Pabst Blue Robot.",
        "Now you know why I used the qualifier 'practically'.",
        "That plot makes perfect sense. Wink, wink.",
        "No I didn't. Raise middle finger.",
        "They're giving out the minor technical awards. I think they're up to Writing.",
        "No, I'm Bender. We met once, remember?",
        "Come on, don't you remember how much I bugged you? Don't you? 'Cause it was a lot. You remember, right?",
        "Bender? That was the other guy. My name's Boiler.",
        "Thanks. And call me Bender.",
        "Of course. I'm a bender. I went to Bending College; I majored in Bending.",
        "Now I can explain that!",
        "Je suis Napoleon! Ha ha ha! No, seriously, I'm not.",
        "You know, like how I live every day.",
        "You were looking up curse words in the dictionary. It seemed like a better use of your time.",
        "Nah.",
        "Eh, I've heard better.",
        "String him up!",
        "I'll give you 300 bucks for it.",
        "Oh, all right. I'll just take these $300 burglar's tools then.",
        "And we made exactly 72 network primetime Emmy-winning episodes!",
        "What's wrong, Big Boots?",
        "It's *vortices* meatbag!",
        "Just tell us what's happening!",
        "I'm Bender, the lovable rascal!",
        "Like everything in life, pumping is just a primitive, degenerate form of bending.",
        "When I grow up, I wanna be a steam shovel!",
        "Maybe blasting this quadrant of space into a hellstorm of flaming nothingness will cheer me up a little.",
        "Aren't those the particles that destroyed an entire civiliza...",
        "Umm, is this the boring, peaceful kind of taking to the streets?",
        "Yes! In your face, Gandhi!",
        "Ooh, a case of strawberry champagne. Don't mind if I do.",
        "Say what?",
        "No liquor? Do svidanya, comrade.",
        "I didn't steal them, I bought them.",
        "That's L.A. for you.",
        "A home invasion by a former room-mate.",
        "Both!",
        "They are bronze.",
        "The name's Bender.",
        "No! It's called parenting.",
        "Alright! You guys are my new best friends!",
        "Am I the only one sittin' here seein' peanut butter on his face?",
        "On the count of three, you will awaken feeling refreshed, as if Futurama were never cancelled by idiots and then brought back by bigger idiots. One... two...",
        "Yeah, we're back.",
        "Woo! I'll just cut that...",
        "Sorry mister, but I'm no Bender. I'm just a simple farmer. Name's Billy West."]

